### ISSUE TITLE
書き込み上限を変更・設定可能に

### ISSUE THREAD

**Issue by SIGESPLIDE** [atomu21263/paint#1]
現状の書き込み上限の2000固定から、変更可能、または特定のIPからのみ書き込みを許可する機能の追加
あるいは、部屋名語尾に特定の文字列を追加することで機能する、自由に描ける部屋、部屋を立てた人のみ書き込み可能な部屋等の追加

**Comment by aatomu** [comment]
https://github.com/atomu21263/paint/commit/dfcfe888058bd22f4fcd78665f561427677b8209
